### ISSUE TITLE
official ?

### ISSUE THREAD

**Issue by maturbet** [Association-Cocktail/ChooseMyCSS#1]
#mantisbt-plugin
Bonjour @dregad,

Seriez-vous intéressé par ce plugin ?

Cordialement,

**Comment by dregad** [comment]
Sure, why not... Here's the process 
https://mantisbt.org/wiki/doku.php/mantisbt:plugins:start#hosting_a_new_plugin

But before that: it is not clear, what you mean by _mandatory_ for a CSS file. This should be explained, maybe in the readme.

A few typos and errors in there to fix
- <del>optionnal</del> => optional
- <del>choosed</del> => chosen
- <del>multy</del> => multi (or maybe multiple ?)
- Changelog: 2013 !? seems like a copy/paste error

Note: I did not actually test or review the code.

**Comment by dregad** [comment]
And https://github.com/Association-Cocktail/ChooseMyCSS/blob/master/ChooseMyCSS.php#L28 maybe better to point to the plugin's home page, someone looking for support will be lost on https://www.asso-cocktail.fr/

**Comment by dregad** [comment]
Another thought... Do you really want to give every single user the ability to add custom CSS ? It can be quite technical and may actually break Mantis if not done right. Maybe better to make this an admin-only feature.

You could also have "global" CSS settings (e.g. from EVENT_MENU_MANAGE) and user-specific ones restricted by a configurable access level.

**Comment by maturbet** [comment]
@dregad 
> Another thought... Do you really want to give every single user the ability to add custom CSS ? It can be quite technical and may actually break Mantis if not done right. Maybe better to make this an admin-only feature.

Actualy, only admin users can add CSS and then, every single user can choose one proposed by admins.

>You could also have "global" CSS settings (e.g. from EVENT_MENU_MANAGE) and user-specific ones restricted by a configurable access level.

Why not in a further version 
I also have some ideas for functional evolutions

**Comment by maturbet** [comment]
Transfered

**Comment by dregad** [comment]
OK thanks. Note that you're maintainer of a dedicated group to manage push access to the repo, should you need to add more contributors.

Don't forget to update various references (e.g. README file, plugin URL, etc) to the new location in mantisbt-plugins.

**Comment by maturbet** [comment]
New location is changed in URLs
